// SPDX-License-Identifier: TBD-private

import XCTest

@testable import MCICaptureHelperKit

final class DenylistTOMLLoaderHappyPathTests: XCTestCase {
    func testEmptyDocumentParsesToZeroEntries() throws {
        let loader = DenylistTOMLLoader()
        let entries = try loader.parse("")
        XCTAssertTrue(entries.isEmpty)
    }

    func testOnlyCommentsAndBlanksParsesToZeroEntries() throws {
        let loader = DenylistTOMLLoader()
        let entries = try loader.parse("""
        # MCI denylist
        # generated by the helper on first run

        # add patterns below
        """)
        XCTAssertTrue(entries.isEmpty)
    }

    func testSingleAppBundleEntry() throws {
        let loader = DenylistTOMLLoader()
        let entries = try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        pattern = "com.1password.1password7"
        """)
        XCTAssertEqual(entries.count, 1)
        XCTAssertEqual(entries[0].kind, .appBundle)
        XCTAssertEqual(entries[0].pattern, "com.1password.1password7")
    }

    func testMultipleEntriesInDocumentOrder() throws {
        let loader = DenylistTOMLLoader()
        let entries = try loader.parse("""
        # password managers
        [[denylist]]
        kind = "appBundle"
        pattern = "com.1password.1password7"

        [[denylist]]
        kind = "appBundle"
        pattern = "com.bitwarden.desktop"

        [[denylist]]
        kind = "urlPrefix"
        pattern = "https://accounts.google.com/"

        [[denylist]]
        kind = "windowTitleSubstring"
        pattern = "Unlock Vault"
        """)
        XCTAssertEqual(entries.count, 4)
        XCTAssertEqual(entries[0].kind, .appBundle)
        XCTAssertEqual(entries[0].pattern, "com.1password.1password7")
        XCTAssertEqual(entries[1].kind, .appBundle)
        XCTAssertEqual(entries[1].pattern, "com.bitwarden.desktop")
        XCTAssertEqual(entries[2].kind, .urlPrefix)
        XCTAssertEqual(entries[2].pattern, "https://accounts.google.com/")
        XCTAssertEqual(entries[3].kind, .windowTitleSubstring)
        XCTAssertEqual(entries[3].pattern, "Unlock Vault")
    }

    func testKeyOrderInsideTableDoesNotMatter() throws {
        let loader = DenylistTOMLLoader()
        let entries = try loader.parse("""
        [[denylist]]
        pattern = "com.x"
        kind = "appBundle"
        """)
        XCTAssertEqual(entries[0].pattern, "com.x")
        XCTAssertEqual(entries[0].kind, .appBundle)
    }

    func testTrailingWhitespaceTolerated() throws {
        let loader = DenylistTOMLLoader()
        let entries = try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        pattern = "com.x"
        """)
        XCTAssertEqual(entries.count, 1)
    }

    /// Loader output is usable by a `Denylist` value directly — the
    /// whole pipeline from TOML to cascade input is tested.
    func testParsedEntriesFeedDenylistMatcher() throws {
        let loader = DenylistTOMLLoader()
        let entries = try loader.parse("""
        [[denylist]]
        kind = "urlPrefix"
        pattern = "https://accounts.google.com/"
        """)
        let denylist = Denylist(entries: entries)
        XCTAssertTrue(denylist.urlIsDenied("https://accounts.google.com/signin"))
        XCTAssertFalse(denylist.urlIsDenied("https://google.com/search"))
    }
}

final class DenylistTOMLLoaderRejectsHostileInputTests: XCTestCase {
    func testRejectsUnexpectedLineOutsideTable() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("kind = \"appBundle\"")) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .unexpectedLine(line: 1))
        }
    }

    func testRejectsMissingKindAtEOF() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        pattern = "com.x"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .missingKind(line: 1))
        }
    }

    func testRejectsMissingPatternAtEOF() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .missingPattern(line: 1))
        }
    }

    func testRejectsMissingKindBetweenTables() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        pattern = "com.x"

        [[denylist]]
        kind = "appBundle"
        pattern = "com.y"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .missingKind(line: 1))
        }
    }

    func testRejectsUnknownKind() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = "bogus_kind"
        pattern = "com.x"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .unknownKind(line: 1, value: "bogus_kind"))
        }
    }

    func testRejectsEmptyPattern() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        pattern = ""
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .emptyPattern(line: 3))
        }
    }

    func testRejectsUnquotedValue() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = appBundle
        pattern = "com.x"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .malformedKvLine(line: 2))
        }
    }

    func testRejectsEscapeSequenceInValue() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        pattern = "com.\\x"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .malformedKvLine(line: 3))
        }
    }

    func testRejectsInnerQuoteInValue() {
        // No escape support means an inner `"` is malformed.
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        pattern = "com."x"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .malformedKvLine(line: 3))
        }
    }

    func testRejectsDuplicateKindInOneTable() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        kind = "urlPrefix"
        pattern = "com.x"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .duplicateKey(line: 3, key: "kind"))
        }
    }

    func testRejectsUnknownKey() {
        let loader = DenylistTOMLLoader()
        XCTAssertThrowsError(try loader.parse("""
        [[denylist]]
        kind = "appBundle"
        pattern = "com.x"
        priority = "high"
        """)) { err in
            XCTAssertEqual(err as? DenylistTOMLError, .malformedKvLine(line: 4))
        }
    }
}
