/* DMG Software License Agreement resources.
 * Auto-generated from docs/legal/terms-of-service.md.
 * Regenerate: python3 assets/installer/generate-eula.py
 *
 * Attach to DMG:
 *   hdiutil unflatten Hippocampus.dmg
 *   Rez -append assets/installer/sla.r -o Hippocampus.dmg
 *   hdiutil flatten Hippocampus.dmg
 */

data 'LPic' (5000) {
    $"0000"  /* default language */
    $"0001"  /* count */
    $"0000"  /* English */
    $"0000"  /* resource ID offset */
    $"0000"  /* reserved */
};

resource 'STR#' (5000, "English buttons") {
    {
        "English",
        "Agree",
        "Disagree",
        "Print",
        "Save\311",
        "If you agree with the terms of this license, click "
        "\"Agree\" to install the software. "
        "If you do not agree, click \"Disagree\"."
    }
};

data 'TEXT' (5000, "English") {
    "Hippocampus Terms of Service\n"
    "\n"
    "Effective date: TBD \n"
    "\n"
    "Last updated: TBD\n"
    "\n"
    "Plain-English summary: Hippocampus is a local-first screen-memory application that runs on your Mac. You own your data. We provide the software as-is, with no warranty. You agree not to use it to capture content you don't have rights to. You can stop using Hippocampus at any time by deleting the app and your data.\n"
    "\n"
    "1. Acceptance\n"
    "\n"
    "By installing, copying, or otherwise using Hippocampus (\"the Software\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree, do not install or use the Software. \n"
    "\n"
    "2. Description of the Software\n"
    "\n"
    "Hippocampus is a desktop application that captures your screen and workflow context, processes it locally on your device using OCR and text embeddings, and stores it in an encrypted local database — your \"brain.\" All processing runs on your Mac. The Software does not transmit your content to any server. See our Privacy Policy (privacy-policy.md) for details.\n"
    "\n"
    "3. License\n"
    "\n"
    "Subject to these Terms, Hippocampus (\"the Company\") grants you a limited, non-exclusive, non-transferable, revocable license to install and use the Software on macOS devices you own or control, for personal or internal business purposes.\n"
    "\n"
    "You may not:\n"
    "\n"
    "- Reverse-engineer, decompile, or disassemble the Software, except to the extent permitted by applicable law \n"
    "- Redistribute, sublicense, rent, lease, or lend the Software to third parties\n"
    "- Remove or alter any proprietary notices, labels, or marks in the Software\n"
    "- Use the Software to provide a competing service or product\n"
    "\n"
    "The Software's source code is proprietary and closed-source. Trust in the Software's privacy and security claims is earned through published third-party security audits, not source access. Audit reports are available at hippocampus.ai/security.\n"
    "\n"
    "3.1 Ownership\n"
    "\n"
    "The Software, including all intellectual property rights therein, is owned by Hippocampus (the Company). These Terms do not grant you any ownership interest in the Software. \n"
    "\n"
    "3.2 Your data\n"
    "\n"
    "You own your data. The brain database, OCR text, embeddings, keyframe blobs, and all other content generated by the Software from your screen belong to you. We claim no ownership, license, or rights over your data. We cannot access your data — it is encrypted on your device with a key we do not hold.\n"
    "\n"
    "4. Acceptable use\n"
    "\n"
    "You agree to use the Software only for lawful purposes and in accordance with these Terms. Specifically, you agree not to:\n"
    "\n"
    "- Capture content you do not have rights to. The Software captures what appears on your screen. You are responsible for ensuring you have the right to record and store the content that appears on your screen. \n"
    "- Circumvent the sensitive-surface cascade. The Software includes a 7-layer sensitive-surface suppression system that blocks capture of password fields, secure-input mode, DRM-protected video, incognito browser windows, and unknown applications. You agree not to modify, disable, or circumvent these protections. \n"
    "- Use the Software for surveillance. The Software is designed for single-user, self-directed use. You may not install or use the Software to monitor another person's screen without their knowledge and consent. \n"
    "- Violate applicable laws. You agree to comply with all applicable local, state, national, and international laws and regulations in your use of the Software, including laws related to data protection, privacy, and intellectual property.\n"
    "\n"
    "5. Hippocampus for Teams\n"
    "\n"
    "If you use Hippocampus for Teams (\"Teams\"), additional terms apply:\n"
    "\n"
    "- Subscription. Teams requires a paid per-seat subscription. Pricing, billing terms, and subscription management are provided at the time of purchase. \n"
    "- Workspace administration. The workspace administrator controls membership. Enrollment requires out-of-band verification by an existing member. See our Privacy Policy §7 (privacy-policy.md) for the encryption architecture.\n"
    "- Content responsibility. Brief content uploaded to a workspace is visible to all enrolled workspace members. You are responsible for reviewing and approving briefs before upload. The Software's brief approval pipeline requires your explicit approval for each brief — no content is auto-uploaded.\n"
    "- Workspace deletion. Workspace deletion crypto-shreds all brief ciphertext after a configurable grace period. Workspace lockout (all admins lose device keys) results in permanent, unrecoverable workspace loss. This is a structural property of the zero-knowledge design. \n"
    "\n"
    "6. Warranty disclaimer\n"
    "\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE,\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.\n"
    "\n"
    "WITHOUT LIMITING THE FOREGOING, HIPPOCAMPUS DOES NOT WARRANT THAT:\n"
    "\n"
    "- THE SOFTWARE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS\n"
    "- THE SOFTWARE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE\n"
    "- THE SENSITIVE-SURFACE SUPPRESSION CASCADE WILL DETECT AND BLOCK ALL SENSITIVE CONTENT IN ALL CIRCUMSTANCES (coverage gaps are documented in ADR-0013 §6 (../decisions/0013-native-grade-sensitive-surface-suppression.md))\n"
    "- THE RESULTS OBTAINED FROM USE OF THE SOFTWARE WILL BE ACCURATE OR RELIABLE\n"
    "- THE ENCRYPTION WILL BE FREE OF ALL VULNERABILITIES\n"
    "\n"
    "You acknowledge that the Software captures and processes screen content locally, and that the accuracy and completeness of OCR, text extraction, and search results depend on factors outside our control (screen resolution, font rendering, application behavior, macOS version).\n"
    "\n"
    "7. Limitation of liability\n"
    "\n"
    "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL HIPPOCAMPUS (THE COMPANY), ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:\n"
    "\n"
    "- YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SOFTWARE\n"
    "- ANY CONTENT CAPTURED, STORED, OR PROCESSED BY THE SOFTWARE\n"
    "- UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR BRAIN DATABASE OR ENCRYPTED STORE\n"
    "- ANY FAILURE OF THE SENSITIVE-SURFACE SUPPRESSION CASCADE TO BLOCK SPECIFIC CONTENT\n"
    "- LOSS OF DATA DUE TO ENCRYPTION KEY LOSS, DEVICE FAILURE, OR WORKSPACE LOCKOUT\n"
    "- ANY OTHER MATTER RELATING TO THE SOFTWARE\n"
    "\n"
    "IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATED TO THE SOFTWARE EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR FIFTY DOLLARS ($50), WHICHEVER IS GREATER. \n"
    "\n"
    "8. Termination\n"
    "\n"
    "8.1 By you\n"
    "\n"
    "You may stop using Hippocampus at any time. To fully terminate:\n"
    "\n"
    "1. Quit Hippocampus.\n"
    "2. Delete the Hippocampus.app application bundle.\n"
    "3. Delete ~/Library/Application Support/MCI/ (your brain database and blobs).\n"
    "4. Optionally delete ~/Library/Logs/MCI/ (local crash and health logs).\n"
    "\n"
    "No account closure is needed because no account exists for the local product.\n"
    "\n"
    "8.2 By us\n"
    "\n"
    "We may terminate or suspend your access to the Software if you violate these Terms. For the local product, \"termination\" means we may revoke your license to use the Software — but because your data is local and encrypted with a key we do not hold, we cannot delete or access your data.\n"
    "\n"
    "For Hippocampus for Teams, termination of a subscription means the workspace server stops serving sync requests. Your local data remains on your device.\n"
    "\n"
    "8.3 Effect of termination\n"
    "\n"
    "Upon termination, you must cease using the Software and delete all copies. Sections 3.2 (your data ownership), 6 (warranty disclaimer), 7 (limitation of liability), 10 (governing law), and 11 (dispute resolution) survive termination. \n"
    "\n"
    "9. Updates\n"
    "\n"
    "Hippocampus may check for updates via the Sparkle auto-update framework. You can disable automatic update checks in the application menu. Updates are signed with an EdDSA key and verified before installation — no tampered update can be installed.\n"
    "\n"
    "We will provide at least 30 days' notice before any update that materially changes the Software's privacy behavior, data collection, or these Terms. If you do not agree with a material change, your remedy is to stop using the Software and uninstall it per §8.1. \n"
    "\n"
    "10. Governing law\n"
    "\n"
    "These Terms shall be governed by and construed in accordance with the laws of [STATE/JURISDICTION TBD], without regard to its conflict of laws provisions.\n"
    "\n"
    "11. Dispute resolution\n"
    "\n"
    "[DISPUTE RESOLUTION MECHANISM TBD]\n"
    "\n"
    "12. Miscellaneous\n"
    "\n"
    "12.1 Entire agreement\n"
    "\n"
    "These Terms, together with the Privacy Policy (privacy-policy.md), constitute the entire agreement between you and Hippocampus regarding the Software. \n"
    "\n"
    "12.2 Severability\n"
    "\n"
    "If any provision of these Terms is held invalid or unenforceable, the remaining provisions remain in full force and effect. \n"
    "\n"
    "12.3 Waiver\n"
    "\n"
    "Our failure to enforce any right or provision of these Terms shall not be considered a waiver of those rights.\n"
    "\n"
    "12.4 Assignment\n"
    "\n"
    "You may not assign or transfer these Terms or your rights under them without our prior written consent. We may assign our rights and obligations under these Terms without restriction. \n"
    "\n"
    "13. Contact\n"
    "\n"
    "For questions about these Terms:\n"
    "\n"
    "- Email: legal@hippocampus.ai \n"
    "- Web: hippocampus.ai/legal\n"
    "\n"
    "These Terms of Service apply to the Hippocampus desktop application distributed by Hippocampus (the company). The engineering codename for the project is MCI (Memory Context Interface).\n"
};

data 'styl' (5000, "English") {
    $"0001"           /* 1 style run */
    $"00000000"       /* start offset */
    $"000C"           /* height */
    $"000A"           /* ascent */
    $"0000"           /* font ID (system) */
    $"0000"           /* face (plain) */
    $"000A"           /* size 10 */
    $"0000 0000 0000" /* color (black) */
};
