//! V2-P5+ Tier-2 supervised-NER machinery — pure-Rust tokenizer (with
//! byte-offset mapping) + BIO span-merge decoder.
//!
//! This is the "P2′" half of the V2-P5+ supervised-NER rework (ratified
//! 2026-06-03, see `memory/project-gliner-variant-pin.md`): the hot-path
//! Tier-2 entity kinds Person / Organization / Location move from the
//! Qwen JSON-prompt backend ([`crate::extraction::tier2`]) to a
//! supervised token-classifier (`dslim/distilbert-NER`, `CoNLL-2003`,
//! `bert-base-cased`). A token-classifier emits per-token logits, not
//! JSON, so two pure-Rust pieces are needed around the Core ML model:
//!
//! - [`tokenizer`] — `WordPiece` tokenization **with byte-offset mapping**
//!   (the embedder's tokenizer discards offsets; the NER decoder needs
//!   them to map labelled tokens back to source byte spans).
//! - [`decoder`] — BIO span-merge, a faithful port of `HuggingFace`'s
//!   `aggregation_strategy="simple"`, turning logits + offsets into
//!   typed byte spans aligned with the V2-P4 entity-kind representation.
//!
//! Neither piece calls Core ML. The future NER backend (the
//! `GLiNERTier2Backend → NerTier2Backend` rename, a later phase) glues
//! [`tokenizer`] → Core ML inference → [`decoder`] →
//! [`crate::extraction::tier2::Tier2RawMatch`], then the existing
//! [`crate::extraction::tier2::Tier2Extractor`] applies the
//! cascade-marker + token-REDACT-downstream filters above it. So a
//! NER-derived mention flows through the SAME composition + persistence
//! path as the Qwen one, tagged `extractor_kind = "qwen"` until the
//! provenance tag is revisited.
//!
//! Date / Time stay on the V2-P4 regex tier; this module covers only the
//! soft / open-vocab Person / Org / Location kinds the regex bank cannot
//! reach.
//!
//! # Gate
//!
//! Both pieces are pinned against committed golden fixtures
//! (`fixtures/distilbert_ner_golden.json`, generated by
//! `fixtures/gen_golden.py` from the real model) — the Rust tokenizer
//! must reproduce HF `input_ids` + byte offsets exactly, and the Rust
//! decoder must reproduce HF's aggregated entity spans exactly. See the
//! `golden_tests` module below.

pub mod decoder;
pub mod tokenizer;

pub use decoder::{decode_bio, decode_distilbert_ner, DecodedSpan, DISTILBERT_NER_ID2LABEL};
pub use tokenizer::{NerEncoded, NerTokenizerError, NerWordPieceTokenizer};

// ===========================================================================
// Golden-fixture tests — the make-or-break gate.
//
// `distilbert_ner_golden.json` is a committed reference dump produced by
// `fixtures/gen_golden.py` running `dslim/distilbert-NER` through the
// `HuggingFace` fast tokenizer + the real `aggregation_strategy="simple"`
// pipeline. These tests assert byte-for-byte parity between the
// pure-Rust implementations and that Python reference.
// ===========================================================================

#[cfg(test)]
mod golden_tests {
    use super::decoder::{decode_distilbert_ner, DISTILBERT_NER_ID2LABEL};
    use super::tokenizer::NerWordPieceTokenizer;
    use serde::Deserialize;

    const GOLDEN: &str = include_str!("fixtures/distilbert_ner_golden.json");
    const CONFIG: &str = include_str!("resources/config.json");

    #[derive(Deserialize)]
    struct Golden {
        id2label: Vec<String>,
        cases: Vec<Case>,
    }

    #[derive(Deserialize)]
    struct Case {
        text: String,
        input_ids: Vec<i32>,
        attention_mask: Vec<i32>,
        special_tokens_mask: Vec<i32>,
        offsets_byte: Vec<(usize, usize)>,
        logits: Vec<Vec<f32>>,
        expected: Vec<Expected>,
        /// Raw HF `aggregation_strategy="simple"` entities BEFORE our
        /// MISC/O filter — used by the corpus-diversity test to assert
        /// the MISC-drop path is actually exercised by real fixtures.
        hf_entities_simple: Vec<HfEntity>,
    }

    #[derive(Deserialize)]
    struct Expected {
        kind: String,
        text: String,
        span_start: usize,
        span_end: usize,
        confidence: f32,
    }

    #[derive(Deserialize)]
    struct HfEntity {
        entity_group: String,
    }

    fn load_golden() -> Golden {
        serde_json::from_str(GOLDEN).expect("golden fixture parses")
    }

    /// The corpus is representative — not just large, but exercising the
    /// load-bearing behaviors: all three kept kinds, the MISC-drop path,
    /// multibyte (non-ASCII) byte offsets, an empty input, and a negative
    /// (no-entity) case. A fixture regeneration that silently lost any of
    /// these would weaken the gate without failing the exact-match tests,
    /// so pin the diversity explicitly.
    #[test]
    fn golden_has_representative_corpus() {
        let g = load_golden();
        assert!(
            g.cases.len() >= 12,
            "expected ≥12 golden cases, got {}",
            g.cases.len()
        );

        // All three kept kinds appear somewhere in the expected output.
        let kinds: std::collections::HashSet<&str> = g
            .cases
            .iter()
            .flat_map(|c| c.expected.iter().map(|e| e.kind.as_str()))
            .collect();
        for k in ["person_name", "organization", "location"] {
            assert!(kinds.contains(k), "no fixture exercises kind {k}");
        }

        // The MISC-drop path is exercised: ≥2 cases where HF emitted a
        // MISC entity that our filter must drop (so it is absent from
        // `expected`).
        let misc_cases = g
            .cases
            .iter()
            .filter(|c| {
                c.hf_entities_simple
                    .iter()
                    .any(|e| e.entity_group == "MISC")
            })
            .count();
        assert!(
            misc_cases >= 2,
            "expected ≥2 fixtures exercising MISC-drop, got {misc_cases}"
        );

        // Byte-offset fidelity is exercised across non-ASCII (multibyte)
        // text in ≥1 case that actually yields a kept entity.
        let multibyte = g
            .cases
            .iter()
            .any(|c| !c.text.is_ascii() && !c.expected.is_empty());
        assert!(multibyte, "no multibyte fixture with a kept entity");

        // An empty input and a negative (no-entity) case are present.
        assert!(
            g.cases.iter().any(|c| c.text.is_empty()),
            "no empty-input case"
        );
        assert!(
            g.cases
                .iter()
                .any(|c| !c.text.is_empty() && c.expected.is_empty()),
            "no negative (non-empty, no-entity) case"
        );
    }

    /// The decoder's compile-time `id2label` matches the real model
    /// `config.json` (read it, don't assume a canonical order).
    #[test]
    fn id2label_matches_bundled_config() {
        let cfg: serde_json::Value = serde_json::from_str(CONFIG).expect("config.json parses");
        let id2label = cfg
            .get("id2label")
            .and_then(|v| v.as_object())
            .expect("config.json has id2label object");
        // config id2label is a {"0":"O","1":"B-PER",...} string-keyed map.
        let mut from_config: Vec<String> = vec![String::new(); id2label.len()];
        for (k, v) in id2label {
            let idx: usize = k.parse().expect("numeric id2label key");
            from_config[idx] = v.as_str().expect("string label").to_string();
        }
        assert_eq!(
            from_config.as_slice(),
            DISTILBERT_NER_ID2LABEL,
            "decoder DISTILBERT_NER_ID2LABEL drifted from model config.json"
        );
        // Cross-pin against the fixture's recorded id2label too.
        assert_eq!(load_golden().id2label, DISTILBERT_NER_ID2LABEL);
    }

    /// (a) The Rust tokenizer reproduces HF `input_ids`,
    /// `attention_mask`, `special_tokens_mask`, and **byte** offsets
    /// EXACTLY on every fixture.
    #[test]
    fn tokenizer_matches_hf_on_every_fixture() {
        let tk = NerWordPieceTokenizer::load_bundled().expect("bundled NER tokenizer loads");
        let g = load_golden();
        for case in &g.cases {
            let enc = tk.encode(&case.text).expect("encode");
            assert_eq!(
                enc.input_ids, case.input_ids,
                "input_ids mismatch for {:?}",
                case.text
            );
            assert_eq!(
                enc.attention_mask, case.attention_mask,
                "attention_mask mismatch for {:?}",
                case.text
            );
            assert_eq!(
                enc.special_tokens_mask, case.special_tokens_mask,
                "special_tokens_mask mismatch for {:?}",
                case.text
            );
            assert_eq!(
                enc.offsets, case.offsets_byte,
                "byte offsets mismatch for {:?}",
                case.text
            );
        }
    }

    /// (b) The Rust BIO decoder, fed the recorded logits, reproduces
    /// HF's `aggregation_strategy="simple"` entity spans EXACTLY (kind +
    /// byte span exact; confidence within a float tolerance) on every
    /// fixture — including MISC-drop, O-drop, multibyte, subword
    /// reassembly, and the messy ALL-CAPS / UI-chrome cases.
    #[test]
    fn decoder_matches_hf_on_every_fixture() {
        let g = load_golden();
        for case in &g.cases {
            let seq_len = case.logits.len();
            let num_labels = DISTILBERT_NER_ID2LABEL.len();
            assert!(
                case.logits.iter().all(|r| r.len() == num_labels),
                "ragged logits in {:?}",
                case.text
            );
            let flat: Vec<f32> = case.logits.iter().flatten().copied().collect();
            assert_eq!(
                case.offsets_byte.len(),
                seq_len,
                "offsets/logits length mismatch for {:?}",
                case.text
            );

            let got = decode_distilbert_ner(
                &case.text,
                &flat,
                seq_len,
                &case.offsets_byte,
                &case.special_tokens_mask,
                &case.attention_mask,
            );

            assert_eq!(
                got.len(),
                case.expected.len(),
                "entity count mismatch for {:?}: got {:?}, want {:?}",
                case.text,
                got.iter()
                    .map(|s| (&s.kind, s.span_start, s.span_end))
                    .collect::<Vec<_>>(),
                case.expected
                    .iter()
                    .map(|e| (&e.kind, e.span_start, e.span_end))
                    .collect::<Vec<_>>(),
            );
            for (got_span, want) in got.iter().zip(&case.expected) {
                assert_eq!(got_span.kind, want.kind, "kind mismatch in {:?}", case.text);
                assert_eq!(
                    got_span.span_start, want.span_start,
                    "span_start mismatch in {:?}",
                    case.text
                );
                assert_eq!(
                    got_span.span_end, want.span_end,
                    "span_end mismatch in {:?}",
                    case.text
                );
                assert_eq!(
                    got_span.text, want.text,
                    "mention text mismatch in {:?}",
                    case.text
                );
                // Tight tolerance: the decoder is fed the SAME float32
                // logits HF used, so the only slack is f32-vs-numpy
                // softmax ULP drift, which is < 1e-7 in practice. 1e-5
                // gives ~100× margin while still catching a real
                // confidence-aggregation bug (e.g. averaging the wrong
                // tokens, or a stale-logits fixture whose argmax did not
                // flip but whose probabilities shifted).
                let dc = (got_span.confidence - want.confidence).abs();
                assert!(
                    dc < 1e-5,
                    "confidence mismatch in {:?}: got {}, want {} (Δ={dc})",
                    case.text,
                    got_span.confidence,
                    want.confidence
                );
            }
        }
    }

    /// End-to-end on EVERY fixture: the Rust tokenizer's own offsets +
    /// masks (NOT the recorded ones) fed straight into the decoder
    /// reproduce the expected spans — proves the two halves compose
    /// without the Python reference in the middle, across the full
    /// corpus including multibyte (CJK, emoji, accents), ALL-CAPS,
    /// empty, and negative cases. This is the test that would catch a
    /// tokenizer/decoder offset-basis mismatch (e.g. a future
    /// `tokenizers` bump flipping byte↔char offsets).
    #[test]
    fn tokenizer_and_decoder_compose_end_to_end() {
        let tk = NerWordPieceTokenizer::load_bundled().expect("load");
        let g = load_golden();
        for case in &g.cases {
            let enc = tk.encode(&case.text).expect("encode");
            let flat: Vec<f32> = case.logits.iter().flatten().copied().collect();
            let got = decode_distilbert_ner(
                &case.text,
                &flat,
                case.logits.len(),
                &enc.offsets, // Rust tokenizer offsets, not the recorded ones
                &enc.special_tokens_mask,
                &enc.attention_mask,
            );
            let got_spans: Vec<(&str, usize, usize)> = got
                .iter()
                .map(|s| (s.kind.as_str(), s.span_start, s.span_end))
                .collect();
            let want_spans: Vec<(&str, usize, usize)> = case
                .expected
                .iter()
                .map(|e| (e.kind.as_str(), e.span_start, e.span_end))
                .collect();
            assert_eq!(
                got_spans, want_spans,
                "compose mismatch for {:?}",
                case.text
            );
            // The decoded mention text must equal the verbatim source
            // substring (the contract the Tier2Extractor verify_span
            // hallucination guard enforces on Tier2RawMatch).
            for s in &got {
                assert_eq!(&case.text[s.span_start..s.span_end], s.text);
            }
        }
    }
}
