#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIGEST_TOOL="$SCRIPT_DIR/product-source-digest.py"
PROVENANCE_TOOL="$SCRIPT_DIR/build-provenance.py"
BUILD_APP="$SCRIPT_DIR/../apps/hippocampus/Resources/build-app.sh"
INSTALLER="$SCRIPT_DIR/build-installer.sh"
LIVE_RUNNER="$SCRIPT_DIR/run-live-capture-overlap.sh"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/hippocampus-source-digest.XXXXXX")"
trap 'rm -rf "$TMP_ROOT"' EXIT

fail() {
    printf 'product source provenance: %s\n' "$1" >&2
    exit 1
}

[[ -x "$DIGEST_TOOL" ]] || fail "digest tool is missing or not executable"
[[ -x "$PROVENANCE_TOOL" ]] || fail "build provenance tool is missing or not executable"
"$BUILD_APP" --help > "$TMP_ROOT/build-help.out"
rg -q -- '--current-source-qualification' "$TMP_ROOT/build-help.out" \
    || fail "app assembly help omits current-source qualification mode"
if "$BUILD_APP" --current-source-qualification > "$TMP_ROOT/release-mode.out" 2>&1; then
    fail "current-source qualification was accepted without --debug"
fi
rg -q 'current-source qualification requires --debug' "$TMP_ROOT/release-mode.out" \
    || fail "release-profile qualification failure is not actionable"
if "$BUILD_APP" --debug --development-ad-hoc --current-source-qualification \
    > "$TMP_ROOT/adhoc-mode.out" 2>&1; then
    fail "current-source qualification was accepted with ad-hoc signing"
fi
rg -q 'current-source qualification requires Developer ID signing' \
    "$TMP_ROOT/adhoc-mode.out" \
    || fail "ad-hoc qualification failure is not actionable"

git -C "$TMP_ROOT" init -q
mkdir -p "$TMP_ROOT/apps/hippocampus" "$TMP_ROOT/target"
printf 'one\n' > "$TMP_ROOT/apps/hippocampus/source.swift"
printf 'ignored\n' > "$TMP_ROOT/target/generated"
printf 'target/\n' > "$TMP_ROOT/.gitignore"
git -C "$TMP_ROOT" add .gitignore apps/hippocampus/source.swift

first="$(python3 "$DIGEST_TOOL" --repo-root "$TMP_ROOT")"
second="$(python3 "$DIGEST_TOOL" --repo-root "$TMP_ROOT")"
[[ "$first" =~ ^[0-9a-f]{64}$ ]] || fail "digest is not lowercase SHA-256"
[[ "$first" == "$second" ]] || fail "unchanged source produced different digests"

printf 'different ignored output\n' > "$TMP_ROOT/target/generated"
ignored_change="$(python3 "$DIGEST_TOOL" --repo-root "$TMP_ROOT")"
[[ "$first" == "$ignored_change" ]] \
    || fail "ignored build output changed the product source digest"
mkdir -p "$TMP_ROOT/scripts/__pycache__"
printf 'generated bytecode\n' > "$TMP_ROOT/scripts/__pycache__/module.cpython-999.pyc"
bytecode_change="$(python3 "$DIGEST_TOOL" --repo-root "$TMP_ROOT")"
[[ "$first" == "$bytecode_change" ]] \
    || fail "generated Python bytecode changed the product source digest"
printf 'apps/hippocampus/Hidden.swift\n' >> "$TMP_ROOT/.git/info/exclude"
printf 'hidden one\n' > "$TMP_ROOT/apps/hippocampus/Hidden.swift"
ignored_source_before="$(python3 "$DIGEST_TOOL" --repo-root "$TMP_ROOT")"
printf 'hidden two\n' > "$TMP_ROOT/apps/hippocampus/Hidden.swift"
ignored_source_after="$(python3 "$DIGEST_TOOL" --repo-root "$TMP_ROOT")"
[[ "$ignored_source_before" != "$ignored_source_after" ]] \
    || fail "an ignored compiler source file escaped the product source digest"

printf 'two\n' > "$TMP_ROOT/apps/hippocampus/source.swift"
source_change="$(python3 "$DIGEST_TOOL" --repo-root "$TMP_ROOT")"
[[ "$first" != "$source_change" ]] \
    || fail "a product source change did not change the digest"

rg -Fq 'build-provenance.json' "$BUILD_APP" \
    || fail "app assembly does not embed source provenance"
rg -Fq 'product-source-digest.py' "$BUILD_APP" \
    || fail "app assembly does not use the canonical digest tool"
rg -Fq 'EXPECTED_QUALIFICATION_TEAM_ID="BV6KGKFKP4"' "$BUILD_APP" \
    || fail "qualification assembly is not pinned to the production Team ID"
rg -Fq '"current_source_qualification": args.current_source_qualification' "$PROVENANCE_TOOL" \
    || fail "app assembly does not attest the qualification rebuild mode"
python3 - "$BUILD_APP" <<'PY'
import sys

source = open(sys.argv[1], encoding="utf-8").read()
developer_branch = source.index('if [[ "$SIGNING_MODE" == "developer-id" ]]')
main_sign = source.index('"$MACOS/Hippocampus"', developer_branch)
provenance = source.index("\n    write_build_provenance\n", main_sign)
outer_sign = source.index('"$APP"', provenance)
if not main_sign < provenance < outer_sign:
    raise SystemExit("Developer ID provenance must hash signed binaries before outer signing")

adhoc_branch = source.index('echo "Codesigning (development-only ad-hoc)..."', outer_sign)
main_sign = source.index('"$MACOS/Hippocampus"', adhoc_branch)
provenance = source.index("\n    write_build_provenance\n", main_sign)
outer_sign = source.index('"$APP"', provenance)
if not main_sign < provenance < outer_sign:
    raise SystemExit("ad-hoc provenance must hash signed binaries before outer signing")
PY
FAKE_APP="$TMP_ROOT/Fake.app"
FAKE_MACOS="$FAKE_APP/Contents/MacOS"
FAKE_RESOURCES="$FAKE_APP/Contents/Resources"
mkdir -p "$FAKE_MACOS" "$FAKE_RESOURCES/Models/Test.mlmodelc"
for binary in Hippocampus MCICaptureHelper mci-agent recall-ui onboarding \
    hippocampus-native-host; do
    printf '%s bytes\n' "$binary" > "$FAKE_MACOS/$binary"
done
printf 'model bytes\n' > "$FAKE_RESOURCES/Models/Test.mlmodelc/weights.bin"
python3 "$PROVENANCE_TOOL" create --app "$FAKE_APP" \
    --source-head 0123456789abcdef --source-digest "$first" \
    --current-source-qualification
python3 "$PROVENANCE_TOOL" verify --app "$FAKE_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source
if python3 "$PROVENANCE_TOOL" verify --app "$FAKE_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --forbid-current-source > /dev/null 2>&1; then
    fail "qualification provenance was accepted as a release artifact"
fi

printf 'signed bytes\n' >> "$FAKE_MACOS/MCICaptureHelper"
if python3 "$PROVENANCE_TOOL" verify --app "$FAKE_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source > /dev/null 2>&1; then
    fail "modified binary still matched build provenance"
fi
if python3 "$PROVENANCE_TOOL" refresh --app "$FAKE_APP" > /dev/null 2>&1; then
    fail "unsafe provenance refresh can bless modified artifacts"
fi
python3 "$PROVENANCE_TOOL" create --app "$FAKE_APP" \
    --source-head 0123456789abcdef --source-digest "$first" \
    --current-source-qualification
python3 "$PROVENANCE_TOOL" verify --app "$FAKE_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source

printf 'different model bytes\n' > "$FAKE_RESOURCES/Models/Test.mlmodelc/weights.bin"
if python3 "$PROVENANCE_TOOL" verify --app "$FAKE_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source > /dev/null 2>&1; then
    fail "modified bundled model still matched build provenance"
fi
python3 "$PROVENANCE_TOOL" create --app "$FAKE_APP" \
    --source-head 0123456789abcdef --source-digest "$first" \
    --current-source-qualification
printf 'unexpected executable\n' > "$FAKE_MACOS/unexpected.dylib"
if python3 "$PROVENANCE_TOOL" verify --app "$FAKE_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source > /dev/null 2>&1; then
    fail "unexpected MacOS payload escaped build provenance"
fi

SIGNED_APP="$TMP_ROOT/Signed.app"
SIGNED_MACOS="$SIGNED_APP/Contents/MacOS"
SIGNED_NESTED="$SIGNED_APP/Contents/Helpers/nested-tool"
mkdir -p "$SIGNED_MACOS" "$SIGNED_APP/Contents/Resources" "$(dirname "$SIGNED_NESTED")"
for binary in Hippocampus MCICaptureHelper mci-agent recall-ui onboarding \
    hippocampus-native-host; do
    cp /usr/bin/true "$SIGNED_MACOS/$binary"
    codesign --force --sign - "$SIGNED_MACOS/$binary" >/dev/null
done
cp /usr/bin/true "$SIGNED_NESTED"
codesign --force --sign - "$SIGNED_NESTED" >/dev/null
python3 - "$SIGNED_APP/Contents/Info.plist" <<'PY'
import plistlib
import sys

with open(sys.argv[1], "wb") as handle:
    plistlib.dump(
        {
            "CFBundleExecutable": "Hippocampus",
            "CFBundleIdentifier": "ai.hippocampus.ProvenanceFixture",
            "CFBundlePackageType": "APPL",
        },
        handle,
    )
PY
python3 "$PROVENANCE_TOOL" create --app "$SIGNED_APP" \
    --source-head 0123456789abcdef --source-digest "$first" \
    --current-source-qualification
codesign --force --sign - "$SIGNED_NESTED" >/dev/null
python3 "$PROVENANCE_TOOL" verify --app "$SIGNED_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source
codesign --force --sign - "$SIGNED_APP" >/dev/null
python3 "$PROVENANCE_TOOL" verify --app "$SIGNED_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source
printf 'synthetic stapler ticket\n' > "$SIGNED_APP/Contents/CodeResources"
python3 "$PROVENANCE_TOOL" verify --app "$SIGNED_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source
printf 'nested payload still belongs to provenance\n' \
    > "$SIGNED_APP/Contents/Resources/CodeResources"
if python3 "$PROVENANCE_TOOL" verify --app "$SIGNED_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --require-current-source > /dev/null 2>&1; then
    fail "a non-ticket CodeResources payload escaped build provenance"
fi
python3 "$PROVENANCE_TOOL" create --app "$SIGNED_APP" \
    --source-head 0123456789abcdef --source-digest "$first"
python3 "$PROVENANCE_TOOL" verify --app "$SIGNED_APP" \
    --expected-source-head 0123456789abcdef --expected-source-digest "$first" \
    --forbid-current-source
if rg -Fq '"$BUILD_PROVENANCE_TOOL" refresh --app "$APP_PATH"' "$INSTALLER"; then
    fail "installer can re-attest modified artifacts during re-signing"
fi
rg -Fq '"$BUILD_PROVENANCE_TOOL" verify --app "$APP_PATH"' "$INSTALLER" \
    || fail "installer does not verify provenance after app stapling"
rg -Fq -- '--forbid-current-source' "$INSTALLER" \
    || fail "installer can package a debug qualification app as a release"
rg -Fq 'source_digest' "$LIVE_RUNNER" \
    || fail "live qualification does not validate embedded source provenance"
rg -Fq 'helper_sha256' "$LIVE_RUNNER" \
    || fail "live qualification evidence does not hash the helper"
rg -Fq 'agent_sha256' "$LIVE_RUNNER" \
    || fail "live qualification evidence does not hash the agent"

printf 'PASS: product source and live artifact provenance are deterministic and fail-closed\n'
