//! Schema DDL for the encrypted MCI store.
//!
//! Each `pub const` below is a single CREATE statement. The Phase-1
//! store-init code executes [`all_ddl`] inside one transaction against a
//! freshly opened SQLCipher-backed connection. There is no `DROP` /
//! `ALTER` here by design — migrations live in their own module and bump
//! [`SCHEMA_VERSION`] explicitly.
//!
//! **Why constants and not a migration runner?** Phase 0 ships no live data
//! and no `rusqlite` dependency yet. Locking the DDL as `&'static str`
//! constants this early makes the schema reviewable as a single artifact and
//! lets adapter code reference the table/column names by string without
//! pulling in a database driver. Phase 1 wires the executor.
//!
//! **CSO sign-off (binding):** any change to the column shapes below —
//! especially `event_vectors.embedding`, the `sync_log` hash-chain columns,
//! or the `meta.schema_version` discipline — requires a fresh CSO review.
//! `AGENT_PROTOCOL` §5 protected-set scope applies (ADRs 0008 + 0012).

/// Monotonic schema version. Bumped on any DDL change (with a paired
/// migration script under `core/src/store/migrations/`). The store-init code
/// refuses to open a database whose `meta.schema_version` is higher than
/// this value.
///
/// Phase 0 ships version 1.
pub const SCHEMA_VERSION: u32 = 1;

// ---------------------------------------------------------------------------
// events / episodes — the retrieval unit per ADR-0010
// ---------------------------------------------------------------------------

/// `events` — the primary retrieval and index unit (ADR-0010).
///
/// `summary` and `entities` are key-expansion fields generated by an
/// idle-time on-device LLM (never on the hot path). `episode_id` is
/// backfilled by the episode segmenter.
pub const CREATE_EVENTS: &str = r#"
CREATE TABLE IF NOT EXISTS events (
    id                INTEGER PRIMARY KEY,
    ts                INTEGER NOT NULL,            -- monotonic capture timestamp (ms since epoch)
    device_id         TEXT    NOT NULL,            -- opaque per-device identifier
    app_bundle        TEXT,                        -- e.g. "com.apple.Safari"
    window_title      TEXT,
    source_type       TEXT    NOT NULL,            -- 'ext' | 'ocr' | 'ax'
    url               TEXT,
    keyframe_blob_ref TEXT,                        -- BLAKE3 hash → blobs.hash
    dwell_ms          INTEGER,
    dhash             INTEGER,                     -- 64-bit perceptual hash
    episode_id        INTEGER REFERENCES episodes(id),
    summary           TEXT,                        -- on-device LLM, idle-time
    entities          TEXT                         -- JSON list, idle-time
);
"#;

/// `episodes` — contiguous app/task run, segmented from the event stream by
/// time-gap + content-shift (dHash distance + embedding-cosine drop over a
/// sliding window). No LLM in the segmenter; cheap.
pub const CREATE_EPISODES: &str = r"
CREATE TABLE IF NOT EXISTS episodes (
    id          INTEGER PRIMARY KEY,
    ts_start    INTEGER NOT NULL,
    ts_end      INTEGER NOT NULL,
    app_bundle  TEXT,
    summary     TEXT,
    entities    TEXT
);
";

/// Index for time-window queries: "show me everything around timestamp X."
pub const CREATE_EVENTS_TS_IDX: &str = "CREATE INDEX IF NOT EXISTS events_ts_idx ON events(ts);";

/// Index for app-scoped recall: "what did I do in VS Code today?"
pub const CREATE_EVENTS_APP_IDX: &str =
    "CREATE INDEX IF NOT EXISTS events_app_idx ON events(app_bundle, ts);";

// ---------------------------------------------------------------------------
// event_text + FTS5 — lexical recall (ADR-0010)
// ---------------------------------------------------------------------------

/// `event_text` — extracted text per event (ext / ocr / ax).
pub const CREATE_EVENT_TEXT: &str = r"
CREATE TABLE IF NOT EXISTS event_text (
    event_id           INTEGER PRIMARY KEY REFERENCES events(id),
    text               TEXT NOT NULL,
    lang               TEXT,                       -- BCP-47 tag
    extraction_method  TEXT NOT NULL               -- 'ext' | 'ocr' | 'ax'
);
";

/// FTS5 virtual table mirroring `event_text.text`. Lexical half of the
/// hybrid retrieval in ADR-0010. FTS5 is compiled into the bundled `SQLCipher`
/// build per ADR-0008.
pub const CREATE_EVENT_TEXT_FTS: &str = r"
CREATE VIRTUAL TABLE IF NOT EXISTS event_text_fts USING fts5(
    text,
    content='event_text',
    content_rowid='event_id'
);
";

// ---------------------------------------------------------------------------
// event_vectors — semantic recall; 384-d pin per ADR-0009
// ---------------------------------------------------------------------------

/// `event_vectors` — sqlite-vec virtual table. Dimension is **384** and
/// **frozen** at this value by ADR-0009. Vectors are stored L2-normalized
/// by the embedder wrapper before insert; the store enforces dimension and
/// nothing else.
///
/// sqlite-vec is loaded as a runtime extension from the bundled path per
/// ADR-0008; the connection refuses to enable extension loading from
/// arbitrary filesystem paths.
pub const CREATE_EVENT_VECTORS: &str = r"
CREATE VIRTUAL TABLE IF NOT EXISTS event_vectors USING vec0(
    event_id  INTEGER PARTITION KEY,
    chunk_id  INTEGER,
    embedding float[384]
);
";

/// `chunks` — sub-units of events that exceed the embedder's effective
/// context window. Each chunk inherits the parent event's context header
/// per ADR-0010.
pub const CREATE_CHUNKS: &str = r"
CREATE TABLE IF NOT EXISTS chunks (
    id          INTEGER PRIMARY KEY,
    event_id    INTEGER NOT NULL REFERENCES events(id),
    ord         INTEGER NOT NULL,                  -- 0-based chunk index within the event
    text        TEXT    NOT NULL,
    token_count INTEGER NOT NULL,
    UNIQUE(event_id, ord)
);
";

// ---------------------------------------------------------------------------
// blobs — content-addressed keyframe / segment store
// ---------------------------------------------------------------------------

/// `blobs` — content-addressed metadata for keyframes / video segments
/// stored on disk. Per ADR-0008 the bytes themselves are encrypted with a
/// per-blob key derived from the DB master key (HKDF, per-blob salt =
/// content hash) — that derivation lives in `core/crypto/` (Phase 1).
pub const CREATE_BLOBS: &str = r"
CREATE TABLE IF NOT EXISTS blobs (
    hash       TEXT PRIMARY KEY,                   -- BLAKE3 of plaintext bytes
    path       TEXT NOT NULL,                      -- relative path within the user blob dir
    bytes      INTEGER NOT NULL,
    codec      TEXT NOT NULL                       -- 'hevc' | 'jpeg' | 'png' | ...
);
";

// ---------------------------------------------------------------------------
// sync_log — append-only, encrypted, hash-chained (ADR-0012 §3)
// ---------------------------------------------------------------------------

/// `sync_log` — the canonical state of MCI. Local `SQLite` tables are a
/// materialized view; the log is the source of truth for sync.
///
/// **Hash-chained** per ADR-0012: each entry's `prev_hash` = BLAKE3 of the
/// prior entry's `(seq || ciphertext || nonce || tag)`. Clients verify the
/// chain from their last-known-good `seq` forward on every sync round.
/// Defends rollback / truncation / key-substitution per Backendal CRYPTO 2024
/// + the ACM CCS 2024 companion paper.
///
/// The server stores opaque ciphertext blobs and a delta log for ordering;
/// it **cannot decrypt anything** (ADR-0001 zero-knowledge invariant).
pub const CREATE_SYNC_LOG: &str = r"
CREATE TABLE IF NOT EXISTS sync_log (
    seq         INTEGER PRIMARY KEY,                -- monotonic, append-only
    device_id   TEXT    NOT NULL,
    op          TEXT    NOT NULL,                   -- 'event-upsert' | 'event-delete' | 'tombstone' | ...
    ciphertext  BLOB    NOT NULL,                   -- AEAD-encrypted payload
    nonce       BLOB    NOT NULL,                   -- per-entry AEAD nonce
    prev_hash   BLOB    NOT NULL,                   -- BLAKE3 over the prior entry; chains the log
    tag         BLOB    NOT NULL                    -- AEAD auth tag over (entry || prev_hash)
);
";

// ---------------------------------------------------------------------------
// user-control records: denylist, redactions, deletions (tombstones)
// ---------------------------------------------------------------------------

/// `denylist` — apps / URL patterns that must never be captured. Enforced at
/// the **source** by the adapter (the frame never enters the pipeline) per
/// DESIGN.md §9.3 + ADR-0012 §9: this is the load-bearing privacy primitive.
pub const CREATE_DENYLIST: &str = r"
CREATE TABLE IF NOT EXISTS denylist (
    id         INTEGER PRIMARY KEY,
    kind       TEXT NOT NULL,                       -- 'app' | 'url_pattern' | 'window_title_pattern'
    pattern    TEXT NOT NULL,
    created_ts INTEGER NOT NULL
);
";

/// `redactions` — patterns the on-device redaction pass applies to OCR text
/// before indexing. Defense-in-depth only (ADR-0012 §9 — secret detection is
/// ~52–88% recall per Basak et al. arXiv:2307.00714).
pub const CREATE_REDACTIONS: &str = r"
CREATE TABLE IF NOT EXISTS redactions (
    id         INTEGER PRIMARY KEY,
    pattern    TEXT NOT NULL,                       -- regex
    replacement TEXT NOT NULL,
    created_ts INTEGER NOT NULL
);
";

/// `deletions` — tombstone records for crypto-shredded ranges per ADR-0012
/// §8. The actual durable delete primitive is destruction of the per-segment
/// key (handled in `core/crypto/` in Phase 1); the tombstone is the log
/// receipt for clients reconstructing state.
pub const CREATE_DELETIONS: &str = r"
CREATE TABLE IF NOT EXISTS deletions (
    id             INTEGER PRIMARY KEY,
    ts_start       INTEGER NOT NULL,
    ts_end         INTEGER NOT NULL,
    segment_key_id TEXT NOT NULL,                  -- the destroyed per-segment key's id (key bytes gone)
    created_ts     INTEGER NOT NULL,
    reason         TEXT                              -- 'user-range' | 'forget-last-hour' | 'denylist-retro' | ...
);
";

// ---------------------------------------------------------------------------
// meta — schema version + key-wrapping metadata + retention policy
// ---------------------------------------------------------------------------

/// `meta` — single-row table holding versioning + key-wrapping pointers +
/// retention policy. Key wrapping metadata = the **public** descriptors
/// (Keychain item identifier, wrap algorithm, salt) — never the wrapped key
/// itself (per ADR-0008, the wrapping is via Secure Enclave and never leaves
/// the OS keystore).
pub const CREATE_META: &str = r"
CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
";

// ---------------------------------------------------------------------------
// Public entry point — ordered DDL for the store-init transaction
// ---------------------------------------------------------------------------

/// Return the full Phase-0 schema as an ordered list of CREATE statements.
///
/// The Phase-1 store-init code executes these inside one transaction
/// against a freshly opened SQLCipher-backed connection. Order matters
/// where `REFERENCES` is involved (episodes before events; events before
/// `event_text` / `event_vectors` / chunks; `sync_log` last).
#[must_use]
pub const fn all_ddl() -> &'static [&'static str] {
    &[
        CREATE_EPISODES,
        CREATE_EVENTS,
        CREATE_EVENTS_TS_IDX,
        CREATE_EVENTS_APP_IDX,
        CREATE_EVENT_TEXT,
        CREATE_EVENT_TEXT_FTS,
        CREATE_EVENT_VECTORS,
        CREATE_CHUNKS,
        CREATE_BLOBS,
        CREATE_SYNC_LOG,
        CREATE_DENYLIST,
        CREATE_REDACTIONS,
        CREATE_DELETIONS,
        CREATE_META,
    ]
}

// ---------------------------------------------------------------------------
// Tests — structural assertions on the DDL constants
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_version_is_one_in_phase_zero() {
        assert_eq!(SCHEMA_VERSION, 1, "Phase 0 ships schema version 1");
    }

    #[test]
    fn every_ddl_constant_is_non_empty() {
        for (i, stmt) in all_ddl().iter().enumerate() {
            assert!(!stmt.trim().is_empty(), "DDL[{i}] is empty");
            assert!(
                stmt.contains("CREATE"),
                "DDL[{i}] does not contain CREATE — likely wrong constant"
            );
        }
    }

    #[test]
    fn event_vectors_dimension_is_pinned_at_384() {
        // ADR-0009 binding invariant. Changing this is a protected-set
        // change requiring a fresh CSO review + a schema-version bump +
        // a re-embed migration.
        assert!(
            CREATE_EVENT_VECTORS.contains("float[384]"),
            "event_vectors.embedding must be float[384] per ADR-0009"
        );
    }

    #[test]
    fn sync_log_carries_hash_chain_columns() {
        // ADR-0012 §3 binding invariant. The hash chain defends against
        // rollback / truncation / key-substitution (Backendal CRYPTO 2024).
        // Removing `prev_hash` or `tag` is a protected-set regression.
        assert!(
            CREATE_SYNC_LOG.contains("prev_hash"),
            "sync_log must carry prev_hash per ADR-0012 §3"
        );
        assert!(
            CREATE_SYNC_LOG.contains("tag"),
            "sync_log must carry AEAD tag per ADR-0012 §3"
        );
    }

    #[test]
    fn deletions_records_segment_key_id_not_plaintext() {
        // ADR-0012 §8 binding invariant. The durable delete primitive is
        // destruction of the per-segment key; the tombstone records only
        // the destroyed key id.
        assert!(
            CREATE_DELETIONS.contains("segment_key_id"),
            "deletions must reference the destroyed per-segment key (ADR-0012 §8)"
        );
    }

    #[test]
    fn events_carries_episode_summary_entities() {
        // ADR-0010 binding invariant. Removing these breaks the event-unit
        // retrieval contract.
        assert!(CREATE_EVENTS.contains("episode_id"));
        assert!(CREATE_EVENTS.contains("summary"));
        assert!(CREATE_EVENTS.contains("entities"));
    }

    #[test]
    fn ddl_order_creates_episodes_before_events() {
        // events.episode_id REFERENCES episodes(id); episodes must exist first.
        let order = all_ddl();
        let epi = order
            .iter()
            .position(|s| s.contains("CREATE TABLE IF NOT EXISTS episodes"))
            .expect("episodes DDL present");
        let evt = order
            .iter()
            .position(|s| s.contains("CREATE TABLE IF NOT EXISTS events "))
            .expect("events DDL present");
        assert!(epi < evt, "episodes must be created before events");
    }
}
